name: Deploy code
description: "Deploy code to a Permanent.org environment"
inputs:
  perm_env:
    description: "dev, staging, or prod"
    required: true
    default: "dev"
  machine:
    description: "backend, cron or taskrunner"
    required: true
    default: "cron"

runs:
    using: "composite"
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Save ssh deploy key to a file
      run: |
        echo "$SSH_KEY" > key
        chmod 400 key
      env:
        SSH_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
    - name: Generate Inventory
      run: ./scripts/generate_inventory.sh dev ${{ inputs.machine }}
    - name: Run deploy
      run: ansible-playbook provisioners/deploy-${{ inputs.machine }}.yml -vv -e "perm_env=${{ inputs.perm_env }}" -i inventory.ini
      env:
        ANSIBLE_PIPELINING: True
        ANSIBLE_HOST_KEY_CHECKING: False

