---
- name: Deploy code on the backend machine and configure cron and services
  hosts: default
  become: true
  vars:
    repos:
        - api
        - daemon
        - library
        - mdot
        - task-runner
        - uploader
        - upload-service
        - website
    temp_dir: /data/tmp/www
    deploy_dir: /data/www
  tasks:
    - name: Create minute cron dir
      file:
        path: /etc/cron.minute
        state: directory
        mode: '0755'
    - name: Add minute crontab
      cron:
        cron_file: /etc/crontab
        user: root
        name: minute crontab
        job: "cd / && run-parts --report /etc/cron.minute"
    - name: Copy packages from S3
      become_user: deployer
      command: "aws s3 cp s3://permanent-repos/{{ perm_env }}/{{ item }}.tar.gz {{ temp_dir }}/{{ item }}.tar.gz"
      loop: "{{ repos }}"
    - name: Untar packages
      unarchive:
         src: "{{ temp_dir }}/{{ item }}.tar.gz"
         dest: "{{ temp_dir }}"
         remote_src: yes
      loop: "{{ repos }}"
    - name: Rsync temprorary directory to deployment directory
      command: "rsync -azh {{ temp_dir }}/{{ item }} {{ deploy_dir }} --delete"
      loop: "{{ repos }}"
    - name: Remove temporary directory
      file:
        path: "{{ temp_dir }}"
        state: absent
    - name: Change file permissions
      file:
        path: "{{ deploy_dir }}"
        state: directory
        recurse: yes
        owner: www-data
        group: deployer
    - name: Create cronjobs
      copy:
        src: "{{ deploy_dir }}/task-runner/scripts/{{ item }}"
        dest: "/etc/cron.{{ item }}"
        owner: www-data 
        group: deployer
        mode: "0744"
        remote_src: yes
      loop:
        - minute/disk-check
        - hourly/resubmit-unprocessed-records
        - hourly/system-check
    - name: Create daemon service files
      copy:
        src: "{{ deploy_dir }}/daemon/scripts/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: www-data 
        group: deployer
        mode: "0644"
        remote_src: yes
      loop:
        - process-daemon.service
        - sqs-daemon.service
    - name: Create uploader service
      copy:
        src: "{{ deploy_dir }}/uploader/scripts/uploader.service"
        dest: /etc/systemd/system/uploader.service
        owner: www-data 
        group: deployer
        mode: "0644"
        remote_src: yes
    - name: Enable and stop all services
      service:
        name: "{{ item }}"
        enabled: yes
        state: stopped
      loop:
        - process-daemon.service
        - sqs-daemon.service
        - uploader.service
        - node-upload.service
    - name: Start all services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - process-daemon.service
        - sqs-daemon.service
        - uploader.service
        - node-upload.service
    - name: Restart apache2
      service:
        name: apache2
        enabled: yes
        state: restarted
