---
- name: Add Users
  hosts: default
  become: true
  tasks: 
    - name: Create user accounts and add them to sudo group
      user:
        name: "{{ item | basename}}"
        groups: "sudo"
        system: no
        createhome: yes
        shell: "/bin/bash"
      with_fileglob:
        - "../ssh/*"
    - name: Add SSH access for users
      authorized_key:
        user: "{{ item | basename }}"
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "../ssh/*"
    - name: Allow sudo without password for sudo group
      copy:
        content: '%sudo  ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/sudo_nopasswd
        mode: 0440

- name: Harden sshd_config
  hosts: default
  become: true
  vars:
    sshd:
      X11Forwarding: no
      UseDNS: yes
      MaxAuthTries: 3
      LoginGraceTime: 20
      AllowAgentForwarding: no
      AllowTcpForwarding: no
  roles:
    - role: willshersystems.sshd

- name: Format and mount persistent storage
  hosts: default
  become: true
  tasks:
    - name: Format filesystem on block device
      filesystem:
        fstype: ext4
        dev: /dev/xvdb
    - name: Mount block device to /data
      mount:
       path: /data
       src: /dev/xvdb
       state: mounted
       fstype: ext4

- name: Perform system configuration 
  hosts: default
  become: true
  tasks:
    - name: Create default code deployment directory
      file:
        path: /data/www
        state: directory
        mode: "0755"
        owner: "www-data"
        group: "deployer"
    - name: Create default log directory
      file:
        path: /var/log/permanent
        state: directory
        mode: "0755"
        owner: "www-data"
        group: "deployer"
