name: Build Dev Image

on:
    workflow_dispatch:

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Validate json
          run: |
            cd images
            packer validate dev.json
    build:
        runs-on: ubuntu-latest
        needs: ["validate"]
        steps:
        - uses: actions/checkout@v1
        - name: Build image
          run: |
            ansible-galaxy install willshersystems.sshd
            cd images
            packer build dev.json
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            HOST: dev
