name: Deploy code to staging 

on:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
          matrix:
            machine: [backend, cron, taskrunner]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        - name: Save ssh deploy key to a file
          run: | 
            echo "$SSH_KEY" > key
            chmod 400 key
          env:
            SSH_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
        - name: Generate Inventory
          run: ./scripts/generate_inventory.sh staging ${{ matrix.machine }}
        - name: Run deploy
          run: ansible-playbook provisioners/deploy-${{ matrix.machine }}.yml -vv -e "perm_env=staging" -i inventory.ini
          env:
            ANSIBLE_PIPELINING: True
            ANSIBLE_HOST_KEY_CHECKING: False
            
