name: Deploy code to dev

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        - name: Save ssh deploy key to a file
          run: 'echo "$SSH_KEY" > key'
          env:
            SSH_KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
        - name: Generate Inventory
          run: ./scripts/generate_inventory.sh
        - name: Run deploy
          run: ansible-playbook provisioners/deploy.yml -vv -e "perm_env=dev" -i inventory.ini
          env:
            ANSIBLE_PIPELINING: True
            HOST_KEY_CHECKING: False
            
