name: Staging code deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
          matrix:
            machine: [backend, cron, taskrunner]
        runs-on: ubuntu-latest
        steps:
        - uses: PermanentOrg/infrastructure@v2
          with:
            perm_env: staging
            machine: ${{ matrix.machine }}
